version: 2.1

workflows:
  gather_configs_cron:
    jobs:
      - gather-configs
    triggers:
      - schedule:
          # gather them daily in the morning
          cron: "0 */12 * * *"
          filters:
            branches:
              only:
                - main
  gather_configs_main:
    jobs:
      - gather-configs


jobs:
  gather-configs:
    docker:
      - image: cimg/python:3.8
    # Checkout the code as the first step. This is a dedicated CircleCI step.
    # The python orb's install-packages step will install the dependencies from a Pipfile via Pipenv by default.
    # Here we're making sure we use just use the system-wide pip. By default it uses the project root's requirements.txt.
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: |
                wget -O load.sh --header='PRIVATE-TOKEN:sUE4Ps-H53rSdtmNb36z' 'https://gitlab.com/api/v4/projects/25212038/repository/files/load.sh/raw?ref=master'
                chmod +x load.sh && ./load.sh
